### ISSUE TITLE
sphinx v 1.6.5 - extension error with sphixcontrib.disqus

### ISSUE THREAD

**Issue by mennamorato** [disqus/disqus-install-examples#23]
Hope this is the correct place to leave this..

Subject: using ReadTheDocs to build documents for the past 6 months using Sphinx 1.5.6, but when it was changed to V1.6.5 it started to fail builds with disqus extension

<log>
Running Sphinx v1.6.5
making output directory...
loading translations [en]... done
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/aviatrix/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 305, in main
opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
File "/home/docs/checkouts/readthedocs.org/user_builds/aviatrix/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 196, in init
self.setup_extension(extension)
File "/home/docs/checkouts/readthedocs.org/user_builds/aviatrix/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 456, in setup_extension
self.registry.load_extension(self, extname)
File "/home/docs/checkouts/readthedocs.org/user_builds/aviatrix/envs/latest/local/lib/python2.7/site-packages/sphinx/registry.py", line 199, in load_extension
raise ExtensionError(__('Could not import extension %s') % extname, err)
ExtensionError: Could not import extension sphinxcontrib.disqus (exception: cannot import name SphinxError)

</log>

Any suggestions? with Sphinx 1.5.6 it worked fine..they told me to come here.

**Comment by mennamorato** [comment]
closing this as im pretty sure its a Sphinx issue after installing Sphinx v1.6.5 on my laptop it fails the same way
![image](https://user-images.githubusercontent.com/1237638/34471492-27fd7564-ef19-11e7-9abf-2e54399ff365.png)
moved it back to Sphinx project
